package com.github.dsmiles.customer;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.time.ZonedDateTime;

import lombok.*;

/**
 * Represents a customer entity in the system.
 * This class is annotated with {@code @Entity} to indicate that it is a JPA entity,
 * meaning it is mapped to a database table.
 * The fields of this class represent attributes of a customer, such as ID, name, and join date.
 * The {@code id} field is annotated with {@code @Id} and {@code @GeneratedValue} to specify that it is
 * the primary key of the entity and that its value will be automatically generated by the database.
 * This class also utilizes Lombok annotations for generating getters, setters, a no-argument constructor,
 * and an all-argument constructor, reducing boilerplate code.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private ZonedDateTime joinedAt;

    public Customer(String name, ZonedDateTime joinedAt) {
        this.name = name;
        this.joinedAt = joinedAt;
    }
}
